<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-09-19 01:20
=======
# Generated by Django 5.0.6 on 2024-09-18 20:21
>>>>>>> 6b3073d0fb68ce09a0dad94671055bba18760aaf

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_department_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_abbreviation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 6b3073d0fb68ce09a0dad94671055bba18760aaf
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_team_name', models.CharField(max_length=32)),
                ('field', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('research_team_logo', models.ImageField(upload_to='research_team_logos/')),
                ('research_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.researchdepartment')),
            ],
        ),
        migrations.AddField(
            model_name='researchdepartment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.school'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=32)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class_name', models.CharField(max_length=30)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=30)),
                ('school_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_name', models.CharField(max_length=32)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_cv', models.FileField(upload_to='students_cvs')),
                ('student_linkedin', models.URLField()),
                ('student_graduation_year', models.PositiveIntegerField()),
                ('school_class_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.schoolclasslevel')),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
=======
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('rdiapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
>>>>>>> 6b3073d0fb68ce09a0dad94671055bba18760aaf
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField(default=1)),
                ('title', models.TextField()),
                ('label', models.CharField(default='project', max_length=32, unique=True)),
                ('keywords', models.TextField()),
                ('objectives', models.TextField()),
                ('deliverables', models.TextField()),
                ('required_skills', models.TextField()),
                ('details', models.FileField(upload_to='research_projects')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('duration_in_weeks', models.PositiveIntegerField()),
                ('more_than_one_intern', models.BooleanField()),
                ('assigned', models.BooleanField(default=False)),
                ('two_supervisors', models.BooleanField(default=False)),
                ('date_proposed', models.DateField(default=datetime.date.today)),
                ('date_assigned', models.DateField(default=datetime.date.today)),
                ('interns', models.ManyToManyField(to='rdiapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField(default=1)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdiapp.project')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rdiapp', to='rdiapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head_supervisor', models.BooleanField(default=False)),
                ('research_team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.researchteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
=======
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher_picture', models.ImageField(upload_to='teacher_pictures/')),
                ('is_head_supervisor', models.BooleanField(default=False)),
                ('research_team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.researchteam')),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.up')),
>>>>>>> 6b3073d0fb68ce09a0dad94671055bba18760aaf
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('rdiapp.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rdiapp', to='rdiapp.teacher'),
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rdiapp', to='rdiapp.teacher'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(to='rdiapp.teacher'),
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_name', models.CharField(max_length=32)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.up'),
        ),
=======
>>>>>>> 6b3073d0fb68ce09a0dad94671055bba18760aaf
    ]
