# Generated by Django 5.0.6 on 2024-07-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchdepartment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.school'),
        ),
    ]
