# Generated by Django 5.0.6 on 2024-07-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchteam',
            old_name='domain',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='application',
            name='highlighted',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rdiapp', to='rdiapp.student'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='highlighted',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.CharField(default='project', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rdiapp', to='rdiapp.teacher'),
        ),
        migrations.AddField(
            model_name='researchdepartment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rdiapp.school'),
        ),
    ]
