# Generated by Django 5.0.6 on 2024-07-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdiapp', '0002_researchdepartment_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchteam',
            old_name='domain',
            new_name='field',
        ),
    ]
